### ISSUE TITLE
default icon displayed even though actual icon exists

### ISSUE THREAD

**Issue by timchr42** [FelixKratz/dotfiles#39]
Hello,

In the spaces tab the icon for some applications, f.e. WhatsApp does not appear even though the corresponding sketchybar-app-icon exists. Any ideas why the app is not recognised/seen as ':default:'? Really curious to know.

![Screenshot 2024-01-20 at 18 27 25](https://github.com/FelixKratz/dotfiles/assets/145785186/c9c31f17-2eed-4645-9b2e-ef9094863be9)

![Screenshot 2024-01-20 at 18 29 38](https://github.com/FelixKratz/dotfiles/assets/145785186/feeb63ad-1d1d-4737-b9bc-9a04de597eec)

Thanks in advance :D

**Comment by FelixKratz** [comment]
Probably because it is not properly contained in the event payload for the space_windows_change event, you can check what is sent through this event when inserting `echo "$INFO"` here:
https://github.com/FelixKratz/dotfiles/blob/8d5754c0a9a217a31a2d9e8caaaf244fe31a8e54/.config/sketchybar/plugins/space_windows.sh#L8
And then running sketchybar from the commandline. See if whatsapp is contained in the apps key for the space where it is opened.

**Comment by timchr42** [comment]
<img width="913" alt="Screenshot 2024-01-21 at 12 43 52" src="https://github.com/FelixKratz/dotfiles/assets/145785186/da198496-5f67-4738-b883-f5a61d6b274f">

This is the output I get when running sketchy bar from command line after inserting `echo "$INFO$"`.
Kind of confused cause this does not seem faulty right?

**Comment by FelixKratz** [comment]
That looks good so far, try inserting `echo "$app"` above this line:
https://github.com/FelixKratz/dotfiles/blob/8d5754c0a9a217a31a2d9e8caaaf244fe31a8e54/.config/sketchybar/plugins/space_windows.sh#L13

**Comment by timchr42** [comment]
<img width="790" alt="Screenshot 2024-01-21 at 14 20 32" src="https://github.com/FelixKratz/dotfiles/assets/145785186/ad7f887f-1950-473f-a3e8-c2153f0411d0">

Also seems fine I guess.

**Comment by FelixKratz** [comment]
So the problem must be in the icon_map file, you could try to copy and paste the output from this command 1:1 into to icon_map file as the key to the whatsapp icon, maybe it is because of some unicode shenanigans.

**Comment by timchr42** [comment]
Too bad, that does also not seem to cause the problem. Pasted the output 1:1.

**Comment by FelixKratz** [comment]
This is wild, will try to look into it because I am also a bit puzzled :D

**Comment by timchr42** [comment]
Yeah, really weird. Bet its something stupid :D 
Tanks a lot for looking into it 🙏

**Comment by FelixKratz** [comment]
Ok so it turns out that whatsapp includes the byte sequence `e2 80 8e` as the leading bytes in their app name, this is the unicode character U+200E and is an invisible control character that indicates that this word shall be printed left to right in all languages, even if they are right to left.... the fix is to include this invisible control character in the icon map.

**Comment by timchr42** [comment]
Oh wow. Nice!

But somehow the terminal icon is fucked up 😂 

<img width="636" alt="Screenshot 2024-01-21 at 16 54 13" src="https://github.com/FelixKratz/dotfiles/assets/145785186/acaadacf-7ec3-4e79-b32f-4ab8d4517f20">

**Comment by FelixKratz** [comment]
You need to update the font, because it contains new icons for the terminals:
```bash
curl -L https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v1.0.23/sketchybar-app-font.ttf -o $HOME/Library/Fonts/sketchybar-app-font.ttf
```

**Comment by timchr42** [comment]
that's what I've realised also xD
But there's still a problem. I guess the key is wrong because in `icon_map.sh` it says `"iTerm"` and not `"iTerm2"`.

**Comment by FelixKratz** [comment]
Oh that might be a regression introduced here:
https://github.com/kvndrsslr/sketchybar-app-font/pull/38
You could report that there so it geta fixed upstream as well

**Comment by timchr42** [comment]
yup, just did
